[package]
name = "solana-escrow"
version = "0.1.0"
edition = "2018"
license = "WTFPL"
publish = false

[dependencies]
solana-program = "1.5.0"
thiserror = "1.0.21"

[lib]
crate-type = ["cdylib", "lib"]
